[package]
name = "firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
critical-section = "1.1.2"
embedded-hal = "0.2.7"
panic-halt = "0.2.0"
rp-pico = { version = "0.8.0", features = ["rp2040-e5"] }
usb-device = "0.2.9"
usbd-hid = "0.5.2"
